name: CI/CD

on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main, develop ]

env:
  APP: "ALO API"
  REGISTRY: ghcr.io  
  
jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Pull codebase
        uses: actions/checkout@v2

      - name: Log in to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}

      - name: Build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}